### PR TITLE
Build deb rpm 10

### PR DESCRIPTION
**Pull request by hantoine**
I set up AppVeyor to build a deb package for Debian.
The deb package for Debian uses an executable built on Debian using docker.
I used AppVeyor cache to skip the Debian environment creation.

@badbouille can you try the deb package for Debian on your machine ?

### CODE REVIEW

**Comment by hantoine** [comment]
You get this error because the version of qml-module-qtquick-controls on Debian stretch (current stable) is 2.0 (corresponding to Qt 5.7), but the QML code ask for the version 2.2. We can either decide not to support Debian stretch since the new Debian stable will come out this year, or change the QML code to use Controls 2.0. I don't know what are the consequences of changing the code, we could try.
https://doc.qt.io/qt-5/qtquickcontrols-index.html#versions

**Comment by badbouille** [comment]
Alright, I removed all 2.2 refereces to QtQuick.Controls as @Seragonia suggested.
The issue disappeared, and the packages needed are **qml-module-qtquick-controls, qml-module-qtquick-controls2, qml-module-qtquick-templates, qml-module-qtquick-dialogs, and maybe sudo** ?
libqt5quickcontrols2-5 did not seem to do anything.

Now, I have this error when starting:
image

Maybe I am still missing a package, or maybe changing all 2.2 references to 2.0 broke the code..

**Comment by hantoine** [comment]
It seems that just replacing the version in the imports is not sufficient to run GostCrypt on Qt 5.7. The error you got comes from the fact that the transition attribute does not exist in QTQuick.Controls 2.0: https://doc.qt.io/archives/qt-5.7/qml-qtquick-controls2-swipedelegate.html

I think it is no longer worth it to support Debian stretch. By the time we have a stable version of GostCrypt ready, Debian stretch will not longer be the last stable, or at least not for long.

**Comment by hantoine** [comment]
I have changed the AppVeyor config to build the deb package for Debian on Debian Buster.
There was a weird bug during compilation, Qt could not find some Qml files. Adding --privileged to the docker run command fixed it. I guess it is related to this docker bug: https://github.com/docker/for-linux/issues/208
@badbouille can you test the deb package on your Debian after updating to Buster ?

**Comment by hantoine** [comment]
I have changed the AppVeyor config to build the deb package for Debian on Debian Buster.
There was a weird bug during compilation, Qt could not find some Qml files. Adding --privileged to the docker run command fixed it. I guess it is related to this docker bug: [docker/for-linux#208](https://github.com/docker/for-linux/issues/208)
@badbouille can you test the deb package on your Debian after updating to Buster ?

**Comment by badbouille** [comment]
So I updated my stretch to buster, and I think I managed to make it work.

First, the package qml-module-qtquick-templates doesn't exist anymore, but I think it worked without it.
Secondly, we need the packages qml-module-qt-labs-folderlistmodel and qml-module-qt-labs-settings.

I didn't test the encryption/decryption yet, but the interface is buggy.. Lots of wrong colors and error messages in console.

**Comment by hantoine** [comment]
OK, I will make these modifications. For the graphical glitch, I have the same issues on my fedora and I created an issue:  https://github.com/GostCryptTeam/gostcrypt/issues/22

**Pull request merged**
